"use client";

import Link from "next/link";
import { useState } from "react";

const modules = [["Clients", "DISPONIBLE"], ["Demandes", "DISPONIBLE"], ["Devis", "DISPONIBLE"], ["Emails", "APERÇU"], ["Interventions", "EN DÉVELOPPEMENT"], ["Documents", "APERÇU"], ["Factures", "EN DÉVELOPPEMENT"], ["Growth", "APERÇU"]] as const;

export function PublicSite() {
  const [diagnosticOpen, setDiagnosticOpen] = useState(false);
  const open = () => setDiagnosticOpen(true);
  return <div className="landing"><LandingHeader onDiagnostic={open} /><main><Hero onDiagnostic={open} /><ProblemSection /><ProcessSection /><DecisionSection /><RoiSection onDiagnostic={open} /><PlatformSection /><FounderSection /><FinalCta onDiagnostic={open} /></main><LandingFooter />{diagnosticOpen ? <DiagnosticDialog onClose={() => setDiagnosticOpen(false)} /> : null}</div>;
}

function LandingHeader({ onDiagnostic }: { onDiagnostic: () => void }) { return <header className="landing-header"><Link href="/" className="landing-logo">SESIRA<span>.</span></Link><nav aria-label="Navigation principale"><a href="#probleme">Le problème</a><a href="#fonctionnement">Comment ça marche</a><a href="#diagnostic">Le calcul</a><a href="#fondateur">Qui je suis</a></nav><button className="landing-button header-cta" onClick={onDiagnostic}>Faire mon diagnostic <b>↗</b></button></header>; }
function Hero({ onDiagnostic }: { onDiagnostic: () => void }) { return <section className="hero"><div className="hero-copy"><p className="eyebrow">SESIRA · chauffage, climatisation, pompes à chaleur</p><h1>Des devis déjà envoyés<br /><em>dorment dans votre boîte mail.</em></h1><p className="hero-lede">Sesira surveille vos devis. Quand un client ne répond pas, il prépare la relance et vous la montre. Vous décidez, il envoie.</p><div className="hero-actions"><button className="landing-button" onClick={onDiagnostic}>Faire mon diagnostic <b>↗</b></button><a className="text-link" href="#fonctionnement">Comprendre en 2 minutes <span>↓</span></a></div><p className="microcopy">Gratuit · 2 minutes · sans engagement</p></div><QuoteCard /></section>; }
function QuoteCard() { return <div className="quote-wrap"><article className="quote-card"><div className="quote-top"><span className="eyebrow dark">EXEMPLE</span><span className="status-badge">RIEN N'EST PARTI</span></div><p className="quote-person">Sophie Lefèvre</p><p className="quote-detail">Pompe à chaleur air/eau · Rhône</p><p className="quote-price">18 450 € <small>HT</small></p><div className="quote-meta"><span>Envoyé<br /><b>il y a 3 jours</b></span><span>Le client a répondu<br /><b>non</b></span></div><div className="quote-note">Aujourd'hui, Sesira relancerait ce client.<br /><strong>Il attend votre feu vert.</strong></div></article></div>; }
function ProblemSection() { return <section id="probleme" className="section paper problem"><div className="section-intro"><p className="eyebrow">01 · LE PROBLÈME</p><h2>Ce devis,<br />vous l'avez<br /><em>déjà payé.</em></h2></div><div className="problem-body"><div className="flow">{["Le client appelle", "Vous vous déplacez", "Vous chiffrez", "Le devis part", "?"] .map((x, i) => <div key={x} className={i === 4 ? "flow-question" : ""}>{x}{i < 4 ? <span>→</span> : null}</div>)}</div><p className="problem-caption">Ce point d'interrogation,<br /><strong>c'est le travail de Sesira.</strong></p><div className="metric-grid"><Metric value="47" label="devis suivis" /><Metric value="12" label="qui dorment" /><Metric value="148 000 €" label="en attente" /><Metric value="4" label="à regarder aujourd'hui" /></div><p className="fiction-note">Exemple de données</p></div></section>; }
function Metric({ value, label }: { value: string; label: string }) { return <div className="metric"><strong>{value}</strong><span>{label}</span></div>; }
function ProcessSection() { return <section id="fonctionnement" className="section paper process"><div className="section-title"><p className="eyebrow">02 · COMMENT ÇA MARCHE</p><h2>Une automatisation<br /><em>qui vous ressemble.</em></h2><p>Sesira ne prend pas les décisions à votre place. Il vous aide à ne plus les rater.</p></div><ol className="process-grid"><Step n="1" title="Il regarde" text="Sesira surveille vos devis, vos échanges et les délais qui passent." /><Step n="2" title="Il vous montre" text="Il vous présente les dossiers qui méritent votre attention, au bon moment." featured /><Step n="3" title="Vous validez" text="Vous gardez la main sur ce qui doit être dit, proposé ou négocié." /><Step n="4" title="Automatisation contrôlée" text="Seulement si vous l'autorisez, selon les règles et limites que vous avez validées." /></ol><p className="process-footnote">Les relances suivent les horaires, la cadence et les limites définis avec votre entreprise. Dès qu'une réponse nécessite votre intervention, Sesira s'arrête.</p></section>; }
function Step({ n, title, text, featured = false }: { n: string; title: string; text: string; featured?: boolean }) { return <li className={featured ? "featured" : ""}><span className="step-number">{n}</span><h3>{title}</h3><p>{text}</p></li>; }
function DecisionSection() { return <section className="section navy decision"><div className="decision-copy"><p className="eyebrow copper">03 · DÉCISION HUMAINE</p><h2>Dès qu'il faut décider,<br /><em>c'est vous.</em></h2><p>Sesira prépare le terrain. Votre expérience reste au centre des décisions qui comptent.</p><article className="reply-card"><div><b>Sophie Lefèvre</b><span>PAC air/eau · 18 450 € HT</span></div><p>« Nous sommes toujours intéressés, mais le tarif dépasse un peu notre budget. »</p><small>Pourquoi Sesira vous le montre</small><strong>Une négociation commerciale nécessite une décision humaine.</strong><div className="reply-actions"><button type="button" disabled>Voir le devis</button><button type="button" disabled>Répondre moi-même</button></div></article></div><div className="decision-side"><p className="eyebrow">RÉPARTITION</p><div className="split"><div><strong>SESIRA<br />S'EN OCCUPE</strong><span>Surveille<br />Prépare<br />Rappelle</span></div><div><strong>VOUS<br />DÉCIDEZ</strong><span>Validez<br />Négociez<br />Engagez</span></div></div></div></section>; }
function RoiSection({ onDiagnostic }: { onDiagnostic: () => void }) { return <section id="diagnostic" className="section paper roi"><div className="section-title"><p className="eyebrow">04 · LE DIAGNOSTIC</p><h2>Quel petit changement<br />suffit pour que Sesira<br /><em>se rembourse ?</em></h2><p>Une simulation simple, basée sur vos vrais devis. Aucune promesse, aucun benchmark.</p></div><div className="roi-layout"><div className="roi-inputs"><RoiRow label="Devis / mois" value="45" /><RoiRow label="Montant moyen" value="12 000 €" /><RoiRow label="Marge" value="30 %" /><RoiRow label="Sesira / mois" value="1 500 €" /><RoiRow label="Installation" value="1 200 €" /></div><div className="roi-result"><p className="eyebrow dark">EXEMPLE DE SIMULATION</p><div className="big-result">6 <small>devis supplémentaires</small></div><div className="roi-lines"><span>Marge par devis <b>3 600 €</b></span><span>Coût année 1 <b>19 200 €</b></span><span>Point de conversion <b>≈ +1,1 point</b></span><span>Volume annuel <b>540</b></span></div><p>Dans cette simulation, environ 6 devis supplémentaires sur l'année couvriraient le coût de la première année.</p></div></div><button className="landing-button" onClick={onDiagnostic}>Calculer avec mes chiffres <b>↗</b></button></section>; }
function RoiRow({ label, value }: { label: string; value: string }) { return <div><span>{label}</span><b>{value}</b></div>; }
function PlatformSection() { return <section className="section navy platform"><div className="section-title"><p className="eyebrow copper">05 · LA PLATEFORME</p><h2>On commence par les devis.<br /><em>Ce n'est pas là que ça s'arrête.</em></h2><p>Plusieurs processus. Une seule logique de suivi.</p></div><div className="platform-columns"><div><p className="eyebrow">CE QU'IL LIT</p><div className="source-card"><span>Devis</span><span>Document</span><span>Facture</span></div></div><div className="today"><p className="eyebrow">À REGARDER AUJOURD'HUI</p><div className="today-card"><b>3 dossiers · 1 décision</b><span>Les devis qui attendent une réponse claire.</span></div></div><div><p className="eyebrow">CE QUE VOUS RECEVEZ</p><div className="received"><b>Une prochaine action</b><span>Au lieu d'une boîte mail à trier.</span></div></div></div><div className="module-list">{modules.map(([name, status]) => <div key={name}><span>{name}</span><small className={status === "DISPONIBLE" ? "available" : ""}>{status}</small></div>)}</div><p className="platform-copy">Le même principe s'applique ailleurs :<br />Sesira surveille, fait le répétitif,<br />et vous remonte ce qui demande une décision.</p></section>; }
function FounderSection() { return <section id="fondateur" className="section paper founder"><div><p className="eyebrow">06 · QUI JE SUIS</p><h2>Un outil pensé<br /><em>depuis le terrain.</em></h2></div><div className="founder-copy"><p>Sesira est né d'une question simple : pourquoi les entreprises qui travaillent le plus dur perdent-elles encore des opportunités dans leurs propres boîtes mail ?</p><p>Je construis Sesira pour les entreprises de chauffage, climatisation et pompes à chaleur qui veulent grandir sans perdre leur façon de travailler.</p><p className="founder-signature">Paul N. Kengué<br /><small>Fondateur de Sesira</small></p></div></section>; }
function FinalCta({ onDiagnostic }: { onDiagnostic: () => void }) { return <section className="final-cta navy"><p className="eyebrow copper">07 · COMMENCER</p><h2>Commencez par<br /><em>vos vrais devis.</em></h2><p>Le premier déploiement peut se concentrer sur vos devis ouverts avant d'étendre Sesira au reste de l'entreprise.</p><button className="landing-button" onClick={onDiagnostic}>Faire mon diagnostic · 2 minutes <b>↗</b></button></section>; }
function LandingFooter() { return <footer className="landing-footer"><Link href="/" className="landing-logo">SESIRA<span>.</span></Link><div><span>Produit</span><a href="#fonctionnement">Comment ça marche</a><a href="#diagnostic">Le diagnostic</a></div><div><span>Accès</span><Link href="/login">Se connecter</Link></div><p>© 2026 Sesira · Suivi des devis pour entreprises CVC</p></footer>; }
function DiagnosticDialog({ onClose }: { onClose: () => void }) { const [values, setValues] = useState({ quotes: "45", amount: "12000", margin: "30", price: "1500", installation: "1200" }); const cost = Number(values.price) * 12 + Number(values.installation); const perQuote = Number(values.amount) * Number(values.margin) / 100; const needed = perQuote ? Math.ceil(cost / perQuote) : 0; const point = Number(values.quotes) ? (needed / Number(values.quotes) / 12 * 100).toFixed(1) : "0.0"; const fit = Number(point) <= 1.5 ? "BON FIT" : Number(point) <= 3 ? "À VÉRIFIER" : "PAS ENCORE ADAPTÉ"; return <div className="dialog-backdrop" role="presentation" onMouseDown={(e) => { if (e.target === e.currentTarget) onClose(); }}><section className="diagnostic-dialog" role="dialog" aria-modal="true" aria-labelledby="diag-title"><button className="dialog-close" onClick={onClose} aria-label="Fermer">×</button><p className="eyebrow dark">DIAGNOSTIC · 2 MINUTES</p><h2 id="diag-title">Vos chiffres, votre seuil.</h2><p className="dialog-lede">Modifiez les hypothèses pour voir quand Sesira se rembourse.</p><div className="dialog-fields">{[["quotes", "Devis par mois"], ["amount", "Montant moyen (€)"], ["margin", "Marge (%)"], ["price", "Prix Sesira / mois (€)"], ["installation", "Installation (€)"]].map(([key, label]) => <label key={key}>{label}<input type="number" min="0" value={values[key as keyof typeof values]} onChange={(e) => setValues({ ...values, [key]: e.target.value })} /></label>)}</div><div className="dialog-result"><span>{fit}</span><strong>{needed} devis</strong><small>supplémentaires nécessaires · ≈ +{point} point de conversion</small></div>{fit === "PAS ENCORE ADAPTÉ" ? <p className="dialog-warning">Avec les chiffres indiqués, Sesira ne semble pas encore économiquement adapté à votre entreprise.</p> : null}<Link href="/diagnostic" className="text-link dark-link" onClick={onClose}>Ouvrir le diagnostic complet ↗</Link></section></div>; }
