-- SESIRA — private document storage
-- Files live under {organization_id}/{object_id}/{safe_filename}.
-- Access is restricted to active members of the organization encoded in the
-- first path segment. The bucket remains private; files are opened through
-- short-lived signed URLs generated by the authenticated server client.

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'sesira-documents',
  'sesira-documents',
  false,
  15728640,
  array['application/pdf', 'image/jpeg', 'image/png', 'image/webp']::text[]
)
on conflict (id) do update
set public = excluded.public,
    file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "sesira_documents_select" on storage.objects;
create policy "sesira_documents_select"
on storage.objects
for select
to authenticated
using (
  bucket_id = 'sesira-documents'
  and case
    when coalesce((storage.foldername(name))[1], '') ~ '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-5][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$'
      then private.is_organization_member(((storage.foldername(name))[1])::uuid)
    else false
  end
);

drop policy if exists "sesira_documents_insert" on storage.objects;
create policy "sesira_documents_insert"
on storage.objects
for insert
to authenticated
with check (
  bucket_id = 'sesira-documents'
  and case
    when coalesce((storage.foldername(name))[1], '') ~ '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-5][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$'
      then private.is_organization_member(((storage.foldername(name))[1])::uuid)
    else false
  end
);

drop policy if exists "sesira_documents_delete" on storage.objects;
create policy "sesira_documents_delete"
on storage.objects
for delete
to authenticated
using (
  bucket_id = 'sesira-documents'
  and case
    when coalesce((storage.foldername(name))[1], '') ~ '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-5][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$'
      then private.is_organization_member(((storage.foldername(name))[1])::uuid)
    else false
  end
);
