import Link from "next/link";

type Connection = { provider: string; status: string; last_sync_at: string | null };
const stateMap: Record<string, { label: string; tone: string; explanation: string }> = {
  CONNECTED: { label: "Connecté", tone: "good", explanation: "La connexion est enregistrée dans votre espace." },
  CONNECTING: { label: "Connexion en cours", tone: "good", explanation: "La connexion est en cours de préparation." },
  DISCONNECTED: { label: "Non connecté", tone: "neutral", explanation: "Les nouvelles réponses ne peuvent pas être synchronisées." },
  REAUTH_REQUIRED: { label: "Action requise", tone: "warning", explanation: "L’autorisation de cette boîte e-mail doit être rétablie." },
  EXPIRED: { label: "Action requise", tone: "warning", explanation: "L’autorisation de cette boîte e-mail a expiré." },
  ERROR: { label: "Problème de connexion", tone: "warning", explanation: "Sesira ne peut pas vérifier correctement cette connexion." },
  FAILED: { label: "Problème de connexion", tone: "warning", explanation: "La dernière tentative de connexion n’a pas abouti." },
  DEGRADED: { label: "Connexion dégradée", tone: "warning", explanation: "La connexion fonctionne partiellement. Les capacités détaillées ne sont pas exposées." },
  PAUSED: { label: "Suspendu", tone: "neutral", explanation: "Cette connexion est actuellement suspendue." },
};
const modeCopy: Record<string, [string, string]> = {
  OBSERVATION: ["Observation", "Aucun message n’est envoyé automatiquement. Sesira utilise la connexion pour observer les échanges disponibles."],
  SHADOW: ["Il vous montre", "Aucun message n’est envoyé automatiquement. Sesira prépare ce qu’il aurait fait."],
  APPROVAL: ["Validation", "Les messages doivent être validés avant tout envoi."],
  AUTOMATIC: ["Automatisation contrôlée", "Les actions autorisées peuvent être exécutées selon les règles configurées. Les décisions sensibles restent humaines."],
};

export function ConnectionsScreen({ connection, mode, organizationPaused, externalActionsEnabled }: { connection: Connection | null; mode: string; organizationPaused: boolean; externalActionsEnabled: boolean }) {
  const state = connection ? stateMap[connection.status] ?? { label: "État inconnu", tone: "neutral", explanation: "L’état fourni par le serveur n’est pas reconnu." } : null;
  const currentMode = modeCopy[mode] ?? modeCopy.OBSERVATION;
  return <div className="connections-page">{organizationPaused ? <div className="connections-pause" role="status"><b>SESIRA EST SUSPENDU POUR CETTE ENTREPRISE</b><p>La connexion peut rester valide, mais aucune action externe n’est exécutée pendant la suspension.</p></div> : null}<header><p className="connections-kicker">RÉGLAGES · CONNEXIONS</p><h1>Connexions</h1><p>Les outils que Sesira utilise pour suivre vos dossiers.</p><small>Commencez par l’adresse e-mail utilisée pour vos devis.</small></header>{connection ? <><article className={`connection-card ${state?.tone}`}><div className="connection-card-head"><div><span>E-MAIL</span><b>{state?.label}</b><p>{providerLabel(connection.provider)}</p></div><span className="connection-health">{state?.tone === "good" ? "EN BON ÉTAT" : state?.label.toUpperCase()}</span></div><div className="connection-body"><p className="connection-explanation">{state?.explanation}</p>{!externalActionsEnabled && connection.status === "CONNECTED" ? <div className="connection-guard"><b>ENVOIS SUSPENDUS</b><p>La connexion e-mail fonctionne, mais Sesira n’exécute actuellement aucune action externe.</p></div> : null}<div className="connection-facts"><Fact label="DERNIÈRE SYNCHRONISATION" value={formatDate(connection.last_sync_at)} note="Horodatage fourni par le serveur" /><Fact label="RÉCEPTION" value="Non exposée" note="État entrant indisponible" /><Fact label="ENVOI" value={externalActionsEnabled ? "Selon votre mode" : "Suspendu"} note="État sortant détaillé indisponible" /></div><section className="connection-capabilities"><b>CETTE CONNEXION PERMET À SESIRA DE</b><p>· reconnaître les échanges liés à vos devis</p><p>· rattacher les échanges aux dossiers lorsque le Core le permet</p><p>· préparer les actions autorisées par votre mode</p></section><section className="connection-mode"><b>SELON VOTRE MODE SESIRA · {currentMode[0]}</b><p>{currentMode[1]}</p></section><p className="connection-actions-blocked">Aucune action de connexion, reconnexion ou déconnexion n’est exposée par le serveur pour le moment.</p></div></article></> : <section className="connection-empty"><h2>Aucune connexion e-mail.</h2><p>Connectez l’adresse utilisée pour vos devis afin que Sesira puisse suivre les échanges.</p><div><b>CONNEXION E-MAIL</b><p>Disponible lorsque l’intégration est activée. Aucun écran d’autorisation n’est simulé ici.</p></div></section>}<section className="connection-other"><b>AUTRES SOURCES</b>{[["Logiciel métier", "SUR DEMANDE"], ["Documents", "APERÇU"], ["Calendrier", "EN DÉVELOPPEMENT"]].map(([name, status]) => <div key={name}><span>{name}</span><small>{status}</small></div>)}<p>Aucune de ces sources n’est connectable aujourd’hui.</p></section><Link href="/app/settings" className="connection-back">← Retour aux réglages</Link></div>;
}
function Fact({ label, value, note }: { label: string; value: string; note: string }) { return <div><span>{label}</span><b>{value}</b><small>{note}</small></div>; }
function providerLabel(provider: string) { const normalized = provider.toLowerCase(); if (normalized.includes("microsoft")) return "Microsoft 365"; if (normalized.includes("google") || normalized.includes("gmail")) return "Google Workspace"; return "Fournisseur e-mail"; }
function formatDate(value: string | null) { if (!value) return "Non exposée"; const date = new Date(value); return Number.isNaN(date.getTime()) ? "Non exposée" : new Intl.DateTimeFormat("fr-FR", { dateStyle: "medium", timeStyle: "short", timeZone: "Europe/Paris" }).format(date); }
